packages:
  - 'packages/*'
  - 'backend/*'

allowBuilds:
  '@nestjs/core': true
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  simple-git-hooks: true
  vue-demi: true
