/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'admin',
    path: '/_internal/admin',
    component: 'layout.base',
    meta: {
      title: 'admin',
      i18nKey: 'route.admin',
      hideInMenu: true
    },
    children: [
      {
        name: 'admin_feedback',
        path: '/_internal/admin/feedback',
        meta: {
          title: 'admin_feedback',
          i18nKey: 'route.admin_feedback',
          icon: 'lucide:messages-square',
          order: 2,
          roles: ['R_ADMIN', 'R_SUPER'],
          hideInMenu: true
        },
        children: [
          {
            name: 'admin_feedback_forms',
            path: '/_internal/admin/feedback/list',
            component: 'view.admin_feedback_forms',
            meta: {
              title: 'admin_feedback_forms',
              i18nKey: 'route.admin_feedback_forms',
              order: 1,
              roles: ['R_ADMIN', 'R_SUPER'],
              hideInMenu: true
            }
          }
        ]
      },
      {
        name: 'admin_users',
        path: '/_internal/admin/users',
        meta: {
          title: 'admin_users',
          i18nKey: 'route.admin_users',
          icon: 'lucide:users-round',
          order: 3,
          roles: ['R_ADMIN', 'R_SUPER'],
          hideInMenu: true
        },
        children: [
          {
            name: 'admin_users_list',
            path: '/_internal/admin/users/list',
            component: 'view.admin_users_list',
            meta: {
              title: 'admin_users_list',
              i18nKey: 'route.admin_users_list',
              order: 1,
              roles: ['R_ADMIN', 'R_SUPER'],
              hideInMenu: true
            }
          }
        ]
      }
    ]
  },
  {
    name: 'feedback',
    path: '/feedback',
    component: 'layout.blank$view.feedback',
    meta: {
      title: 'feedback',
      i18nKey: 'route.feedback',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'feedbackmanage',
    path: '/admin/feedback',
    component: 'layout.base',
    meta: {
      title: 'feedbackmanage',
      i18nKey: 'route.feedbackmanage',
      icon: 'lucide:messages-square',
      order: 2,
      roles: ['R_ADMIN', 'R_SUPER']
    },
    children: [
      {
        name: 'feedbackmanage_list',
        path: '/admin/feedback/list',
        component: 'view.feedbackmanage_list',
        meta: {
          title: 'feedbackmanage_list',
          i18nKey: 'route.feedbackmanage_list',
          order: 1,
          roles: ['R_ADMIN', 'R_SUPER']
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'lucide:house',
      order: 1,
      roles: ['R_ADMIN', 'R_SUPER']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'usermanage',
    path: '/admin/users',
    component: 'layout.base',
    meta: {
      title: 'usermanage',
      i18nKey: 'route.usermanage',
      icon: 'lucide:users-round',
      order: 3,
      roles: ['R_ADMIN', 'R_SUPER']
    },
    children: [
      {
        name: 'usermanage_list',
        path: '/admin/users/list',
        component: 'view.usermanage_list',
        meta: {
          title: 'usermanage_list',
          i18nKey: 'route.usermanage_list',
          order: 1,
          roles: ['R_ADMIN', 'R_SUPER']
        }
      }
    ]
  }
];
